### ISSUE TITLE
Outside the Valid Range

### ISSUE THREAD

**Issue by qops1981** [spodskubka/RemoteTerminal#7] opened 2017-01-30 23:49 UTC
The moment I try to open a connection to an SSH endpoint I simply get in duplicate: "The operation attempt to access data outside the valid range" on a black background with a green outlined cursor rectangle.
I have not tested any other kind of connection, but I mainly use SSH.

**Comment by spodskubka** [comment] 2017-03-06 22:58
This is a duplicate of #3, which will be fixed soon.

**Closed by spodskubka** 2017-03-06 22:58 UTC
Labels: bug, duplicate

**Comment by spodskubka** [comment] 2017-03-06 23:00
@qops1981 FYI: #3 was already closed but I re-opened it since the issue was not resolved in this repository. Thanks for reporting it anyway!
