### ISSUE TITLE
Cant connect to localhost

### ISSUE THREAD

**Issue by tabrarg** [spodskubka/RemoteTerminal#6] opened 2017-01-10 06:38 UTC
I believe this is a limitation of windows store apps, however I have managed to bypass this for other apps by using fiddler. With remote terminal I get the error message "The operation attempted to access data outside the valid range".

It would be really great if I could use remote terminal to SSH onto VMs running on my localhost.

**Comment by tabrarg** [comment] 2017-01-11 19:02
Just to add - I also get the same error trying to SSH to my FreeBSD VM hosted by Digital Ocean :(

**Comment by spodskubka** [comment] 2017-03-06 23:03
The "data outside the valid range" part of this is a duplicate of #3, which I have re-opened recently.

As for the limitation that Windows Store Apps cannot connect to localhost: that is correct, this is (by default) explicitly forbidden.
I have to do some research whether this still holds true for Windows 10 UWP apps, maybe the restriction was lifted for those.

**Comment by tabrarg** [comment] 2017-03-07 06:19
Great - I will have a look at #3 

Thanks!

**Comment by spodskubka** [comment] 2017-03-28 19:57
The localhost restriction is unchanged for Windows 10 UWP apps.

However, your bypass using Fiddler should work correctly as soon as the update for Remote Terminal is released in a few days.

**Closed by spodskubka** 2017-03-28 19:57 UTC
Labels: bug, duplicate
